from decouple import config


TWITCH_APP_NAME = config("TWITCH_APP_NAME", cast=str)
TWITCH_CLIENT_ID = config("TWITCH_CLIENT_ID", cast=str)
TWITCH_CLIENT_SECRET = config("TWITCH_CLIENT_SECRET", cast=str)

DATABASE_URL = config("DATABASE_URL", cast=str)

INSTAGRAM_APP_NAME = config("INSTAGRAM_APP_NAME", cast=str)
INSTAGRAM_CLIENT_ID = config("INSTAGRAM_CLIENT_ID", cast=int)
INSTAGRAM_CLIENT_SECRET = config("INSTAGRAM_CLIENT_SECRET", cast=str)
INSTAGRAM_ACCOUNT_USERNAME = config("INSTAGRAM_ACCOUNT_USERNAME", cast=str)
INSTAGRAM_ACCOUNT_PWD = config("INSTAGRAM_ACCOUNT_PWD", cast=str)
