"""init

Revision ID: ca6cc9fe9e5f
Revises: 
Create Date: 2021-04-05 14:44:31.974041

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ca6cc9fe9e5f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
